# Create Standing Order
create_standing_order:
  target:
    entity:
      integration: rooster_money
  fields:
    amount:
      required: True
      selector:
        number:
          step: 0.1
          unit_of_measurement: GBP
          mode: box
    day:
      required: False
      selector:
        select:
          options:
            - Monday
            - Tuesday
            - Wednesday
            - Thursday
            - Friday
          mode: dropdown
    frequency:
      required: True
      selector:
        select:
          options:
            - Weekly
            - Monthly
            - Daily
    tag:
      required: True
      selector:
        select:
          options:
            - Other
            - Home
    title:
      required: True
      selector:
        text:
          multiline: False
delete_standing_order:
  target:
    entity:
      integration: rooster_money
  fields:
    regular_id:
      required: True
      selector:
        text:
          multiline: False
get_standing_orders:
  target:
    entity:
      integration: rooster_money
perform_action_on_job:
  target:
    entity:
      integration: rooster_money
      domain: sensor
  fields:
    action:
      required: True
      selector:
        select:
          options:
            - Approve
            - Skip
            - Not done
    job_id:
      required: True
      selector:
        number:
          mode: box
update_allowance:
  target:
    entity:
      integration: rooster_money
      domain: sensor
  fields:
    amount:
      required: True
      selector:
        number:
          step: 0.1
          unit_of_measurement: GBP
          mode: box
    active:
      boolean:
boost_pot:
  target:
    entity:
      integration: rooster_money
      domain: sensor
  fields:
    amount:
      required: True
      selector:
        number:
          step: 0.01
          unit_of_measurement: GBP
          mode: box
